#!/bin/bash

if [ $(whoami) != "root" ] ; then
	echo "Should be run as root"
	exit 2
fi
if [ -z $1 ] ; then
	echo "Usage: $0 [request_config_id]"
	exit 1
fi

template_id=$1

config_file="/etc/aws-cli-utils/$template_id-aws-request.json.ejs"
current_user_data_b64=$(cat $config_file | grep UserData | tail -n 1 | cut -d '"' -f 4)
echo $current_user_data_b64 | base64 -d > /tmp/aws-cli-utils-$template_id

vim /tmp/aws-cli-utils-$template_id

new_user_data_b64=$(cat /tmp/aws-cli-utils-$template_id | base64 -w 0)
cat $config_file | sed "s/$current_user_data_b64/$new_user_data_b64/g" > "$config_file.tmp"
mv "$config_file.tmp" $config_file

