#!/bin/sh
if [ -z "$1" ] ; then
	ip=$(aws ec2 describe-instances --query "Reservations[0].Instances[0].NetworkInterfaces[0].Association.PublicIp" --filters "Name=instance-state-name,Values=running" | sed -e 's/^"//' -e 's/"$//')
else
	ip=$1
fi
if [ -z "$(ssh-keygen -F $ip)" ]; then
	# Still vulnerable to MITM since host key is not verified
	ssh-keyscan -H $ip >> ~/.ssh/known_hosts
fi
ssh -i ~/.ssh/aws-laptop.pem ec2-user@$ip
