#!/bin/bash

function create_fleet_tagging_role() {
    cat << 'EOF' > /tmp/aws-cli-utils/fleet-tagging-role-trust-policy
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "spotfleet.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
    aws iam create-role --role-name aws-ec2-spot-fleet-tagging-role --assume-role-policy-document file:///tmp/aws-cli-utils/fleet-tagging-role-trust-policy >> /dev/null
    sleep 4
    aws iam attach-role-policy --role-name aws-ec2-spot-fleet-tagging-role --policy-arn arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole
    sleep 4
}

if [ -z $1 ] ; then
	request_id='default'
else
	request_id=$1
fi
splot_fleet_request_config="/etc/aws-cli-utils/$request_id-aws-request.json"
if [ ! -f "$splot_fleet_request_config" ] ; then
	if [ -f "$splot_fleet_request_config.ejs" ] ; then
		if [ -z "$AWS_CLI_UTILS_DEFAULT_KEY_NAME" ] ; then
			echo "Which AWS key pair should be used ?"
			read key_name
			echo "The key pair file should be placed in ~/.ssh and named $key_name.pem"
			echo "Set the environment variable AWS_CLI_UTILS_DEFAULT_KEY_NAME to set the key pair to use for next times"
		else
			key_name="$AWS_CLI_UTILS_DEFAULT_KEY_NAME"
		fi
		mkdir -p /tmp/aws-cli-utils
                subnets=$(aws ec2 describe-subnets --query "Subnets[].SubnetId" --filters "Name=defaultForAz,Values=true" --output text | sed "s/\t/, /g")
                iam_fleet_role=$(aws iam get-role --role-name aws-ec2-spot-fleet-tagging-role --query Role.Arn --output text 2>> /dev/null)
                if [ "$?" -ne "0" ] ; then  # the role does not exists
                    create_fleet_tagging_role
                    iam_fleet_role=$(aws iam get-role --role-name aws-ec2-spot-fleet-tagging-role --query Role.Arn --output text)
                fi
		cat $splot_fleet_request_config.ejs \
                    | sed "s/<%= KEY_NAME %>/$key_name/g" \
                    | sed "s/<%= SUBNETS %>/$subnets/g" \
                    | sed "s#<%= IAM_FLEET_ROLE %>#$iam_fleet_role#g" \
                    > /tmp/aws-cli-utils/$request_id-aws-request.json
		splot_fleet_request_config="/tmp/aws-cli-utils/$request_id-aws-request.json"
	else
		echo "No config for $request_id"
		exit 1
	fi
fi
command="aws ec2 request-spot-fleet --spot-fleet-request-config file://$splot_fleet_request_config --query \"SpotFleetRequestId\""
fleet_request_id=$($command | sed -e 's/^"//' -e 's/"$//')
if [ "$?" -ne "0" ] ; then
	exit
fi

# Knowing the AMI is useful later for aws-ssh to directly know the user to connect with
ami=$(cat "$splot_fleet_request_config"  | grep ImageId | head -n 1 | cut -d '"' -f 4)

echo "Waiting for Spot request to be processed..."
sleep 10 # It takes at least 10s, no point checking earlier
AWS_CLI_UTILS_DEFAULT_KEY_NAME=$key_name aws-wait-request $fleet_request_id $ami
