#!/bin/sh
if [ -z "$1" ] ; then
	ip=$(aws ec2 describe-instances --query "Reservations[0].Instances[0].NetworkInterfaces[0].Association.PublicIp" --filters "Name=instance-state-name,Values=running" | sed -e 's/^"//' -e 's/"$//')
	if [ "$ip" = "null" ] ; then
		echo "No Instance running"
		exit 1
	fi
else
	ip=$1
fi

if [ -z "$AWS_CLI_UTILS_DEFAULT_KEY_NAME" ] ; then
	echo "Which AWS key pair should be used ?"
	read key_name
	echo "The key pair file should be placed in ~/.ssh and named $key_name.pem"
	echo "Set the environment variable AWS_CLI_UTILS_DEFAULT_KEY_NAME to set the key pair to use for next times"
else
	key_name="$AWS_CLI_UTILS_DEFAULT_KEY_NAME"
fi
ssh -i ~/.ssh/$key_name.pem ec2-user@$ip
