#!/bin/sh -x
aws ec2 describe-instances --query "Reservations[].Instances[].{ID:InstanceId,IPs:NetworkInterfaces[0].Association.PublicIp,Type:InstanceType,AZ:Placement.AvailabilityZone}" --filters "Name=instance-state-name,Values=running" 

