#!/bin/sh
if [ "$#" -lt 1 ]; then
	echo "Usage: aws-list [instance-type] (availability-zone)"
	exit
fi

which gdate >> /dev/null
if [ "$?" -eq 0 ] ; then
    date_cmd='gdate'
else
    date_cmd='date'
fi
command="aws ec2 describe-spot-price-history \
	 --start-time $($date_cmd -Ihours --utc) \
         --output json \
	 --filters \
		Name=product-description,Values=Linux/UNIX \
		Name=instance-type,Values=$1"
if [ ! -z "$2" ] ; then
	command="$command Name=availability-zone,Values=$2"
fi

exec $command
